# Generated by Django 2.2.6 on 2019-11-19 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='identificationCard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='lastName',
            field=models.CharField(default='blank', max_length=25),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='blank', max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
