# Generated by Django 3.0 on 2020-01-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191119_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='glucose',
            field=models.DecimalField(decimal_places=2, default=3.9, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=20, max_length=3),
        ),
    ]
