# Generated by Django 2.2.5 on 2019-09-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190929_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identificationCard',
            field=models.IntegerField(),
        ),
    ]
